// frontend/src/app/components/navbar/navbar/navbar.component.ts
import {Component, ElementRef, HostListener} from '@angular/core';
import {provideTablerIcons, TablerIconComponent} from 'angular-tabler-icons';
import {
  IconAppsFilled,
  IconCategory2,
  IconCategoryFilled,
  IconLogout,
  IconMenu2,
  IconUserFilled
} from 'angular-tabler-icons/icons';
import {RouterLink} from '@angular/router';
import {UserService} from '../../../services/user.service';
import {LoadingSmallComponent} from '../../lib/loaders/loading-small/loading-small.component';

@Component({
  selector: 'app-navbar',
  imports: [
    TablerIconComponent,
    RouterLink,
    LoadingSmallComponent

  ],
  templateUrl: './navbar.component.html',
  styles: `
  `,
  providers: [
    provideTablerIcons({
      IconCategory2,
      IconUserFilled,
      IconLogout
    })
  ]
})
export class NavbarComponent {

  constructor(protected userService: UserService, private eRef: ElementRef) {

  }

  showUserPanel: boolean = false;

  toggleUserPanel(): void {
    this.showUserPanel = !this.showUserPanel;
  }

  handleLogoutButton(): void {
    this.userService.logout();
  }

  // Hostlisteners
  @HostListener('document:click', ["$event"])
  onClickOutside(event: Event): void {
    if (this.showUserPanel && !this.eRef.nativeElement.contains(event.target)) {
      this.showUserPanel = false;
    }
  }

  @HostListener('document:keydown.escape')
  onEscape(): void {
    this.showUserPanel = false;
  }
}

<div class="fixed top-0 left-0 w-full h-12 flex gap-4 items-center justify-between p-2 px-16 bg-prim-dark text-background shadow-xl z-40">

  <!-- Left Side -->
  <div class="flex items-center gap-4">
    <a routerLink="/" ><h1 class="font-semibold text-xl border-r pr-4 cursor-pointer hover:text-prim-light">API-Monitor</h1></a>

    <a routerLink="/dashboard" class="relative flex items-center justify-center cursor-pointer">
      <i-tabler name="category-2" class="hover:text-prim-light"></i-tabler>
    </a>

    <a routerLink="/docs/getting-started" class="cursor-pointer hover:text-prim-light">Getting Started</a>
    <a routerLink="/docs" class="cursor-pointer hover:text-prim-light">Docs</a>
  </div>

  <!-- Right Side -->
  <div class="flex items-center gap-4">

    @if (this.userService.authUser) {
      <div
        class="relative flex items-center justify-center "
      >
        <div (click)="toggleUserPanel()" class="cursor-pointer bg-white text-prim  hover:bg-prim hover:text-white p-1 rounded-full shadow-none flex items-center justify-center">
          <i-tabler name="user-filled"></i-tabler>
        </div>


        @if (this.showUserPanel) {
          <div class="bg-white absolute left-1/2 top-full -translate-x-1/2 rounded flex flex-col p-2 text-foreground">

            <button class="inline-flex gap-2 hover:bg-prim hover:text-white duration-300 p-2 rounded cursor-pointer" (click)="handleLogoutButton()" [disabled]="this.userService.isLoggingOut">
              @if (!this.userService.isLoggingOut) {
                <i-tabler name="logout"></i-tabler>
                <span>Logout</span>
              } @else {
                <loading-small></loading-small>
              }
            </button>

          </div>
        }

      </div>
    } @else {
      <a routerLink="/login" class="cursor-pointer hover:text-prim-light">Login</a>
      <a routerLink="/signup"><button class="submit-btn">Sign Up</button></a>
    }




  </div>



</div>

// frontend/src/components/Navbar.tsx
'use client';

import React from 'react';
import {
  RiArticleLine,
  RiDashboardLine,
  RiLoginBoxLine,
  RiLoginCircleLine,
  RiRadarLine,
  RiRocketLine, RiUserLine
} from "@remixicon/react";
import Link from "next/link";
import {useQuery} from "@tanstack/react-query";
import {fetchAuthUser} from "@/lib/util/AuthUtil";
import {User} from "@/types/AuthTypes";

const Navbar = () => {

  const {data: authUser} = useQuery<User | undefined | null>({
    queryKey: ['authUser'],
    queryFn: fetchAuthUser
  })

  return (
    <div className="fixed top-0 left-0 w-full h-16 bg-dark px-8 py-2 flex items-center justify-between relative">

      {/* Brand */}
      <Link href="/" className="inline-flex items-center gap-2 text-xl font-semibold text-light">
        <RiRadarLine className="text-primary" />
        <span>Vax Monitor</span>
      </Link>

      <nav className="flex items-center gap-8 absolute left-1/2 -translate-x-1/2">

        <Link href="/applications" className="inline-flex items-center gap-2 text-gray-300 font-semibold hover:text-light duration-200">
          <RiDashboardLine />
          <span>Applications</span>
        </Link>

        <Link href="/docs" className="inline-flex items-center gap-2 text-gray-300 font-semibold hover:text-light duration-200">
          <RiArticleLine />
          <span>Docs</span>
        </Link>

        <Link href="/docs/getting-started" className="inline-flex items-center gap-2 text-gray-300 font-semibold hover:text-light duration-200">
          <RiRocketLine />
          <span>Getting Started</span>
        </Link>
      </nav>

      <div className="flex items-center gap-4">

        {!authUser && (
          <>
            <Link href="/login" className="inline-flex items-center gap-2 text-gray-300 font-semibold hover:text-light duration-200">
              <RiLoginCircleLine />
              <span>Login</span>
            </Link>

            <Link href="/signup" className="submit-btn">
              <RiLoginBoxLine />
              <span>Signup</span>
            </Link>
          </>
        )}
        {authUser && (
          <Link href="/profile" className="rounded-md flex items-center justify-center py-1 px-2 hover:bg-secondary-transparent duration-200 cursor-pointer">
            <div className="bg-primary rounded-full p-1 text-light">
              <RiUserLine />
            </div>
          </Link>
        )}


      </div>

    </div>
  );
};

export default Navbar;
